language: php
cache: false

sudo: false

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install

script:
  - composer run ci

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml